name: Primeiro Continuous Delivery
on: 
    push:
        branches: [ main ]

permissions:
  contents: read

jobs:
  Teste_Delivery:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Iniciando CD!!!"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulando Continuous Delivery!!!
        uses: actions/upload-artifact@v7
        with:
          name: projetoZipado.zip
          path: |
            **.py
            README.md

  Teste_Deploy:
    runs-on: ubuntu-latest
    needs: Teste_Delivery
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: projetoZipado.zip
      - name: Mostrar estrutura dos arquivos baixados!
        run:  ls -R
