name: Primeiro Continuous Integration Workflow
on: 
    pull_request:
        branches: [ main ]
        

jobs:
  Nome_do_job_Tosin:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Iniciando teste CI"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Python code
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

          